//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pt_BR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portfolio.Strings.pt-BR", typeof(pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        internal static string About_me {
            get {
                return ResourceManager.GetString("About me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOBRE.
        /// </summary>
        internal static string ABOUT_ME___UpperCase_ {
            get {
                return ResourceManager.GetString("ABOUT ME [#UpperCase]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avançado.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idade.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALISSON RUBIM.
        /// </summary>
        internal static string ALISSON_RUBIM___UpperCase_ {
            get {
                return ResourceManager.GetString("ALISSON RUBIM [#UpperCase]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Análise e Desenvolvimento de Sistemas.
        /// </summary>
        internal static string Analysis_and_systems_development {
            get {
                return ResourceManager.GetString("Analysis and systems development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e muito café.
        /// </summary>
        internal static string and_a_lot_of_coffee {
            get {
                return ResourceManager.GetString("and a lot of coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desenvolvimento Back-End.
        /// </summary>
        internal static string Back_End_Development {
            get {
                return ResourceManager.GetString("Back-End Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Básico.
        /// </summary>
        internal static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brasileiro nascido em Minas Gerais, sou um rapaz apaixonado por tecnologia e que logo cedo descobriu que seu hobby de programador poderia se tornar uma profissão. Desde os 14 anos busquei aprender e aprimorar meus conhecimentos, começando com o básico do C e descobrindo com o tempo a minha vocação para o desenvolvimento web..
        /// </summary>
        internal static string Brazilian_born_in_Minas_Gerais__I_am_a_young_man_in_love_with_technology_and_soon_discovered_that_his_hobby_as_a_programmer_could_become_a_profession__From_the_age_of_14_I_tried_to_learn_and_improve_my_knowledge__starting_with_the_basics_of_C_and_discovering_over_time_my_vocation_for_web_development_ {
            get {
                return ResourceManager.GetString(@"Brazilian born in Minas Gerais, I am a young man in love with technology and soon discovered that his hobby as a programmer could become a profession. From the age of 14 I tried to learn and improve my knowledge, starting with the basics of C and discovering over time my vocation for web development.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique aqui para conhecer mais alguns de meus projetos.
        /// </summary>
        internal static string Clique_here_to_know_more_about_my_projects {
            get {
                return ResourceManager.GetString("Clique here to know more about my projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciência da Computação.
        /// </summary>
        internal static string Computer_science {
            get {
                return ResourceManager.GetString("Computer science", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criado e idealizado por.
        /// </summary>
        internal static string Created_and_idealized_by {
            get {
                return ResourceManager.GetString("Created and idealized by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco de dados.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acadêmico.
        /// </summary>
        internal static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACADÊMICO.
        /// </summary>
        internal static string EDUCATION___UpperCase_ {
            get {
                return ResourceManager.GetString("EDUCATION [#UpperCase]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglês.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desenvolvimento Front-End.
        /// </summary>
        internal static string Front_End_Development {
            get {
                return ResourceManager.GetString("Front-End Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullstack Developer.
        /// </summary>
        internal static string Fullstack_Developer {
            get {
                return ResourceManager.GetString("Fullstack Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullstack Developer e Designer por hobby.
        /// </summary>
        internal static string Fullstack_Developer_and_Designer_by_hobby {
            get {
                return ResourceManager.GetString("Fullstack Developer and Designer by hobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eu sou o Alisson Rubim.
        /// </summary>
        internal static string I_m_Alisson_Rubim {
            get {
                return ResourceManager.GetString("I\'m Alisson Rubim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participei de vários projetos, colaborando com o máximo do meu conhecimento e dividindo experiências com os outros colaboradores..
        /// </summary>
        internal static string I_participated_in_several_projects__collaborating_to_the_best_of_my_knowledge_and_sharing_experiences_with_other_collaborators_ {
            get {
                return ResourceManager.GetString("I participated in several projects, collaborating to the best of my knowledge and" +
                        " sharing experiences with other collaborators.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informática Industrial e Automação.
        /// </summary>
        internal static string Industrial_Informatics_and_Automation {
            get {
                return ResourceManager.GetString("Industrial Informatics and Automation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediário.
        /// </summary>
        internal static string Intermediate {
            get {
                return ResourceManager.GetString("Intermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nunca é tarde para aprender a desenvolver..
        /// </summary>
        internal static string It_s_never_too_late_to_learn_how_to_develop_ {
            get {
                return ResourceManager.GetString("It\'s never too late to learn how to develop.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Línguas.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feito com.
        /// </summary>
        internal static string Made_with {
            get {
                return ResourceManager.GetString("Made with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desenvolvimento Mobile.
        /// </summary>
        internal static string Mobile_Development {
            get {
                return ResourceManager.GetString("Mobile Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meus dados.
        /// </summary>
        internal static string My_informations {
            get {
                return ResourceManager.GetString("My informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nativo.
        /// </summary>
        internal static string Native {
            get {
                return ResourceManager.GetString("Native", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate.
        /// </summary>
        internal static string Navigate {
            get {
                return ResourceManager.GetString("Navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        internal static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projetos.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJETOS.
        /// </summary>
        internal static string PROJECTS___UpperCase_ {
            get {
                return ResourceManager.GetString("PROJECTS [#UpperCase]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilidades.
        /// </summary>
        internal static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HABILIDADES.
        /// </summary>
        internal static string SKILLS___UpperCase_ {
            get {
                return ResourceManager.GetString("SKILLS [#UpperCase]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espanhol.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seja bem-vindo(a),.
        /// </summary>
        internal static string Welcome_ {
            get {
                return ResourceManager.GetString("Welcome,", resourceCulture);
            }
        }
    }
}
