//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Strings {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pt_BR() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portfolio.Strings.pt-BR", typeof(pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sobre.
        /// </summary>
        internal static string About_me {
            get {
                return ResourceManager.GetString("About me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Avançado.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idade.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Análise e Desenvolvimento de Sistemas.
        /// </summary>
        internal static string Analysis_and_systems_development {
            get {
                return ResourceManager.GetString("Analysis and systems development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a e muito café.
        /// </summary>
        internal static string and_a_lot_of_coffee {
            get {
                return ResourceManager.GetString("and a lot of coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desenvolvimento Back-End.
        /// </summary>
        internal static string Back_End_Development {
            get {
                return ResourceManager.GetString("Back-End Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Básico.
        /// </summary>
        internal static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Brasileiro nascido em Minas Gerais, sou um rapaz apaixonado por tecnologia e que logo cedo descobriu que seu hobby de programador poderia se tornar uma profissão. Desde os 14 anos busquei aprender e aprimorar meus conhecimentos, começando com o básico do C e descobrindo com o tempo a minha vocação para o desenvolvimento web..
        /// </summary>
        internal static string Brazilian_born_in_Minas_Gerais__I_am_a_young_man_in_love_with_technology_and_soon_discovered_that_his_hobby_as_a_programmer_could_become_a_profession__From_the_age_of_14_I_tried_to_learn_and_improve_my_knowledge__starting_with_the_basics_of_C_and_discovering_over_time_my_vocation_for_web_development_ {
            get {
                return ResourceManager.GetString(@"Brazilian born in Minas Gerais, I am a young man in love with technology and soon discovered that his hobby as a programmer could become a profession. From the age of 14 I tried to learn and improve my knowledge, starting with the basics of C and discovering over time my vocation for web development.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clique aqui para conhecer mais alguns de meus projetos.
        /// </summary>
        internal static string Clique_here_to_know_more_about_my_projects {
            get {
                return ResourceManager.GetString("Clique here to know more about my projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ciência da Computação.
        /// </summary>
        internal static string Computer_science {
            get {
                return ResourceManager.GetString("Computer science", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Criado e idealizado por.
        /// </summary>
        internal static string Created_and_idealized_by {
            get {
                return ResourceManager.GetString("Created and idealized by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Banco de dados.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Design.
        /// </summary>
        internal static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Acadêmico.
        /// </summary>
        internal static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ACADÊMICO.
        /// </summary>
        internal static string EDUCATION___UpperCase_ {
            get {
                return ResourceManager.GetString("EDUCATION [#UpperCase]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inglês.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desenvolvimento Front-End.
        /// </summary>
        internal static string Front_End_Development {
            get {
                return ResourceManager.GetString("Front-End Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fullstack Developer.
        /// </summary>
        internal static string Fullstack_Developer {
            get {
                return ResourceManager.GetString("Fullstack Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fullstack Developer e Designer por hobby.
        /// </summary>
        internal static string Fullstack_Developer_and_Designer_by_hobby {
            get {
                return ResourceManager.GetString("Fullstack Developer and Designer by hobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GuideMe é um joguinho 2D feito para estimular crianças a aprender mais sobre desenvolvimento..
        /// </summary>
        internal static string GuideMe_is_a_2D_game_made_to_stimulate_children_to_learn_more_about_development_ {
            get {
                return ResourceManager.GetString("GuideMe is a 2D game made to stimulate children to learn more about development.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Eu sou o Alisson Rubim.
        /// </summary>
        internal static string I_m_Alisson_Rubim {
            get {
                return ResourceManager.GetString("I\'m Alisson Rubim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Eu participei de vários projetos, colaborando com o melhor do meu conhecimento e compartilhando experiências com outros colaboradores..
        /// </summary>
        internal static string I_participated_in_several_projects__collaborating_to_the_best_of_my_knowledge_and_sharing_experiences_with_other_collaborators_ {
            get {
                return ResourceManager.GetString("I participated in several projects, collaborating to the best of my knowledge and" +
                        " sharing experiences with other collaborators.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informática Industrial e Automação.
        /// </summary>
        internal static string Industrial_Informatics_and_Automation {
            get {
                return ResourceManager.GetString("Industrial Informatics and Automation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Intermediário.
        /// </summary>
        internal static string Intermediate {
            get {
                return ResourceManager.GetString("Intermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nunca é tarde para aprender como programar..
        /// </summary>
        internal static string It_s_never_too_late_to_learn_how_to_develop_ {
            get {
                return ResourceManager.GetString("It\'s never too late to learn how to develop.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Línguas.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Feito com.
        /// </summary>
        internal static string Made_with {
            get {
                return ResourceManager.GetString("Made with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desenvolvimento Mobile.
        /// </summary>
        internal static string Mobile_Development {
            get {
                return ResourceManager.GetString("Mobile Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Meus dados.
        /// </summary>
        internal static string My_informations {
            get {
                return ResourceManager.GetString("My informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nativo.
        /// </summary>
        internal static string Native {
            get {
                return ResourceManager.GetString("Native", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Navigate.
        /// </summary>
        internal static string Navigate {
            get {
                return ResourceManager.GetString("Navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Português.
        /// </summary>
        internal static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Projetos.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Habilidades.
        /// </summary>
        internal static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Espanhol.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O jogo é interessante pois com ele é possível programar as ações do boneco, com simples comandos, mostrando para quem esta apredendo como funciona a lógica da programação..
        /// </summary>
        internal static string The_game_is_interesting_because_it_is_possible_to_program_the_actions_of_the_doll_with_simple_commands__showing_to_those_who_are_learning_how_the_programming_logic_works_ {
            get {
                return ResourceManager.GetString("The game is interesting because it is possible to program the actions of the doll" +
                        " with simple commands, showing to those who are learning how the programming log" +
                        "ic works.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seja bem-vindo(a),.
        /// </summary>
        internal static string Welcome_ {
            get {
                return ResourceManager.GetString("Welcome,", resourceCulture);
            }
        }
    }
}
